# SPDX-License-Identifier: GPL-2.0
ARG BASE
FROM $BASE

ARG BASE
ARG RUN_CMD

COPY --chmod=0555 src/test/${RUN_CMD}.sh /test.sh

ENTRYPOINT [ "python3" ]

LABEL org.opencontainers.image.description="bare bones Python 3 container"
