# SPDX-License-Identifier: GPL-2.0
ARG BASE_IMAGE
FROM ubuntu:18.04

ARG RUN_CMD

RUN apt -y update && apt -y upgrade && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y \
	build-essential \
	git \
	wget \
	python \
	python-h5py \
	python-scipy \
	python-numpy \
	python-sklearn \
	python-pandas \
	python-bitarray \
	python-pysam \
	python-pip \
	zlib1g-dev

RUN pip install pybedtools plinkio

WORKDIR /src
RUN git clone https://github.com/yiminghu/AnnoPred.git && \
	 git clone https://github.com/bulik/ldsc.git
WORKDIR /src/AnnoPred
RUN echo "LDSC_path /src/ldsc" > LDSC.config

# Source code will be root/root, so to allow for adding
# the required ref files to the AnnoPred directory, we need
# to change the permissions. Unfortunately, the 'ref' directory
# is too large to place into the container, but MUST be in the same
# directory as the AnnoPred source code.
RUN chmod 777 .

ARG TEST="/test.sh"
COPY --chmod=0555 src/test/$RUN_CMD.sh ${TEST}
